const equipmentsAndFacilities = [
  { id: 1, value: "elevator", label: "آسانسور" },
  { id: 2, value: "wallPaper", label: "کاغذ دیواری" },
  { id: 3, value: "chiller", label: "چیلر" },
  { id: 4, value: "parking", label: "پارکینگ" },
  { id: 5, value: "oven", label: "گاز رو میزی" },
  { id: 6, value: "waterCooler", label: "کولر آبی" },
  { id: 7, value: "warehouse", label: "انباری" },
  { id: 8, value: "hood", label: "هود" },
  { id: 9, value: "heater", label: "بخاری" },
  { id: 10, value: "wallCloset", label: "کمد دیواری" },
  { id: 11, value: "masterBathroom", label: "حمام مستر" },
  { id: 12, value: "package", label: "پکیج" },
  { id: 13, value: "painting", label: "نقاشی" },
  { id: 14, value: "pool", label: "استخر" },
  { id: 15, value: "radiator", label: "رادیاتور" },
  { id: 16, value: "terrace", label: "تراس" },
  { id: 17, value: "sauna", label: "سونا" },
  { id: 18, value: "waterHeater", label: "آبگرم کن" },
  { id: 19, value: "antiTheftDoor", label: "درب ضد سرقت" },
  { id: 20, value: "hotTub", label: "جکوزی" },
  { id: 21, value: "airConditioner", label: "کولر گازی" },
  { id: 22, value: "iPhone", label: "آیفون تصویری" },
  { id: 23, value: "lobby", label: "لابی" },
  { id: 24, value: "heating", label: "شوفاژ" },
  { id: 25, value: "camera", label: "دوربین مدار بسته" },
  { id: 26, value: "roofGarden", label: "روف گاردن" },
  { id: 27, value: "underfloorHeating", label: "گرمایش از کف" },
  { id: 28, value: "wc", label: "سرویس فرنگی" },
  { id: 29, value: "gym", label: "سالن ورزش" },
  { id: 30, value: "airMaker", label: "هواساز" },
];

export default equipmentsAndFacilities;
