import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const persianFont = localFont({
  src: "./fonts/persian-font.ttf",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${persianFont.className} antialiased`}>{children}</body>
    </html>
  );
}
